---

env:
  es6: true

extends:
  - airbnb
  - prettier

parser: babel-eslint

rules:
  arrow-parens:
    - 2
    - as-needed
  semi:
    - 2
    - never
  comma-dangle:
    - 2
    - always-multiline
  no-unused-expressions: 0
  no-param-reassign:
    - 2
    - props: false
  no-useless-escape: 0
  func-names: 0
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true
  object-curly-newline: 0
  function-paren-newline: 0
  operator-linebreak:
    - 2
    - after
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/anchor-is-valid:
    - 2
    - specialLink:
        - to
  react/prop-types: 0
  react/jsx-filename-extension: 0
  react/jsx-first-prop-new-line:
    - 2
    - never
  react/jsx-indent-props:
    - 2
    - 2
  react/jsx-closing-bracket-location:
    - 1
    - selfClosing: after-props
      nonEmpty: after-props
  react/prefer-stateless-function:
    - 1
    - ignorePureComponents: true
  react/jsx-boolean-value:
    - 2
    - always
  react/no-unused-prop-types: 0
  import/no-unresolved: 0
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0

